### PR TITLE
add conv4_stride to VGG4LayerActFrontendV1

### PR DESCRIPTION
**Pull request by michelwi**
As discussed in https://github.com/rwth-i6/i6_models/pull/17#issuecomment-1601361410 we wanted to add stride parameter to (at least) the conv4 layer.

Do we want strides at the other layers, too?

### CODE REVIEW

**Comment by christophmluscher** [comment]
This module does the striding via the pooling layers, not the convolutional layers.

We would need to discuss if this is a new module or the same... I find that there are already a lot of parameters here...

**Comment by michelwi** [comment]
> We would need to discuss if this is a new module or the same.

I had the impression it was intended to add down sampling also via conv layers.. 

>  I find that there are already a lot of parameters here...

that's an argument that we might as well add another one xP

**Comment by SimBe195** [comment]
Imo pooling strides and conv strides are not really an "either-or" case, sometimes you might want to have both, e.g. conv strides over time-axis and pooling over feature-axis. So I would not create a new module for this. But for consistency I would add the config parameter for all of the conv layers, not just `conv4`.

**Comment by albertz** [comment]
Just as a reference, the implementation we have in RETURNN frontend (earlier RETURNN-common):
https://github.com/rwth-i6/returnn/blob/a8ffd0b734e0d7fc03a92575019253a31b50075a/returnn/frontend/encoder/conformer.py#L82

This can handle most of our older TF-based setups as well as ESPnet setups.

The strides of convolutions are configurable, and the strides of the poolings are just the same as the pool size (which are configurable) (which is the common case of pooling).

**Comment by christophmluscher** [comment]
> that's an argument that we might as well add another one xP

true

> I had the impression it was intended to add down sampling also via conv layers..

I don't remember, but I am also fine with both

> But for consistency I would add the config parameter for all of the conv layers, not just conv4.

I think this is a good point.

**Comment by christophmluscher** [comment]
more generic and flexible frontend in PR #39. close

**Pull request closed without merging**
